### ISSUE TITLE
Error with data types while trying to train a torch model.

### ISSUE THREAD

**Issue by michaelriveraweb** [ncsa/DRYML#8]
[dry_undamped_try_error.zip](https://github.com/ncsa/DRYML/files/11638975/dry_undamped_try_error.zip)

System information:
    Jupyter Notebook Running on HAL OnDeman HPC
    OS Platform: Linux
    DRYML version: 0.2.1 
    Python version: 3.9.12
    CUDA Version: 11.7 
    GPU model and memory: Tesla V100-SXM2-16GB

When trying to train model, it gives the following error: Found dtype Double but expected Float.
Datatype should be float32, since it was preprocessed with dryml.data.transforms.Cast.

**Comment by krafczyk** [comment]
Okay, I found the issue, it looks like the 'X' component of the data is having the cast applied, but the 'Y' component is now. This is because for the `Cast` transform, the `mode` option sets which components to cast. This is `'X'` by default, but if we change to `'all'`, or add another `Cast` with mode `'Y'` this should hit the `'Y'` component. However with `'all'`, now I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/context/process.py", line 34, in run
    super().run()
  File "/home/mkrafcz2/.conda/envs/opence-v1.6.1-drymldev/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/context/process.py", line 186, in __call__
    self.final_call(f, ctx_send_q, ctx_ret_q, *args, **kwargs)
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/context/process.py", line 129, in final_call
    res = f(*args, **kwargs)
  File "/tmp/ipykernel_39258/3209787140.py", line 19, in train_model
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/context/process.py", line 268, in wrapped_func
    res = f(*args, **kwargs)
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/models/pipe.py", line 37, in train
    step.train(
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/context/process.py", line 268, in wrapped_func
    res = f(*args, **kwargs)
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/models/torch/generic.py", line 135, in train
    self.train_fn(
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/context/process.py", line 268, in wrapped_func
    res = f(*args, **kwargs)
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/models/torch/generic.py", line 188, in __call__
    total_batches = data.count()
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/data/dataset.py", line 256, in count
    for e in self:
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/data/util.py", line 84, in nested_batcher
    el = next(it)
  File "/home/mkrafcz2/HAL_Projects/DRYML/src/dryml/data/util.py", line 119, in nested_unbatcher
    d = next(it)
TypeError: <lambda>() missing 1 required positional argument: 'y'
```

This says to me that something is working properly in the transforms when handling the `'all'` case.
